### ISSUE TITLE
Hello World! done incorrectly

### ISSUE THREAD

**Issue by hallocbr1** [CITIntroToProg1516-7/TestProgram#5]
Hello World'!'

**Comment by ghost** [comment]
ლ(~•̀︿•́~)つ︻̷┻̿═━一
I am now holding this comment thread hostage
ლ(~•̀︿•́~)つ︻̷┻̿═━一

**Comment by hcps-womackcz** [comment]
Try: `System.out.println("Hello World");`

Do I get extra credit now????

**Comment by hcps-wangq** [comment]
الله أكبر
