### ISSUE TITLE
I don't understand this code

### ISSUE THREAD

**Issue by hcps-traceync** [CITIntroToProg1516-7/TestProgram#7]
`    public static void main(String[] args){
        while (true){               while (true){
-         System.out.println("Hello World");
         break;                  break;
      }               }
   }           }`

This does not make cents to me. I see this person is trying the advanced maneuver of the "while true break" but it is horribly executed. His technique is far from stellar and he is not even using a ternary operator. 

EDIT: I tried uninstalling java and installing El Capitan but it still doesn't werk? 
EDIT EDIT: So it seems like the communist overlord has locked this thread rip in pepes Adam Smith is rolling in his grave X(

**Comment by hcps-vanderzrs** [comment]
Try using more break statements :+1:

**Comment by SeanofLaRochelle** [comment]
Needs more break...

**Comment by cmneville** [comment]
`this is code`

**Comment by ghost** [comment]
GG noob u didnt even format it. how am i sposed to read it now pleb? git gud or git off the forums.

**Comment by ghost** [comment]
`GG noob u didnt even format it. how am i sposed to read it now pleb? git gud or git off the forums.`
